# Generated by Django 3.1.1 on 2020-09-09 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('const', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdt',
            name='Right_id',
        ),
        migrations.AddField(
            model_name='cdt',
            name='left_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='left', to='const.const'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cdt',
            name='right_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='right', to='const.const'),
            preserve_default=False,
        ),
    ]
