# Generated by Django 3.1.1 on 2020-09-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('const', '0002_auto_20200909_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='const',
            name='key',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
