# Generated by Django 3.1.1 on 2020-09-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('const', '0003_const_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='const',
            old_name='key',
            new_name='k',
        ),
    ]
